/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.ukui.ScreenSaver.xml -i interface.h -a interfaceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "interfaceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ScreenSaverAdaptor
 */

ScreenSaverAdaptor::ScreenSaverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ScreenSaverAdaptor::~ScreenSaverAdaptor()
{
    // destructor
}

void ScreenSaverAdaptor::Lock()
{
    // handle method call org.ukui.ScreenSaver.Lock
    QMetaObject::invokeMethod(parent(), "Lock");
}

